version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  flask:
    build: ./app
    container_name: flask_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
